version: "3"

services:
  api:
    container_name: mern-api
    restart: always
    build: ./api
    ports:
      - "4000:4000"
    links:
      - mongo
    volumes:
      - ./api:/usr/src/app
  mongo:
    container_name: mern-api-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./api/database:/data/db
    logging:
      driver: none
  app:
    container_name: mern-app
    stdin_open: true
    restart: always
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes: 
      - ./frontend:/usr/src/app
    